名字: Keep Hugging Face Space Awake (bash)

on:
  schedule:
    - cron: "0 * * * *"   # 每小时执行一次（整点）
  workflow_dispatch:

jobs:
  keepalive:
    runs-on: ubuntu-latest
    env:
      URL: "https://xuemm-askjdh.hf.space/"   # <- 根据需要修改
      MAX_ATTEMPTS: 3
      BASE_SLEEP: 5
    steps:
      - name: Ping Space with retries
        run: |
          set -euo pipefail

echo “ ping $URL”
尝试= 1
          while while [$attempt -le $MAX_ATTEMPTS]；做 $attempt -le $MAX_ATTEMPTS ]; do
status=$（curl -sS -o /dev
ull -w "%{http_code}" -H "Authorization: Bearer $HF_TOKEN" "$URL" || echo "000"）: Bearer $HF_TOKEN" "$URL" || echo "000")
            echo 返回“尝试$尝试-> HTTP $状态”
            if 如果["$status" = "200"]；然后 "$status" = "200" ]; then
              echo echo “✅空间可达（HTTP 200）。”
              exit 0
            fi

            if [ $attempt -lt $MAX_ATTEMPTS ]; then
              sleep_seconds=$(( BASE_SLEEP * attempt ))
              echo "Waiting $sleep_seconds seconds before retry..."
              sleep $sleep_seconds
            fi
            attempt=$((attempt + 1))
          done

          echo "::error::All attempts failed. Last HTTP status: $status"
          exit 1
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
